title: Moniyum's Travels
description: >- 
  The travels of the plushie red panda 'Moniyum'. 
url     : https://glasnt.com 
baseurl : /moniyum 
title   : moniyum
title_left         : "glasnt.com"

permalink: /:title
markdown: kramdown
remote_theme: glasnt/myrtle@thinkspace
plugins:
  - jekyll-feed


navbar:
  - slug : /
    title: home
  - slug : /blog/about/
    title: about
  - slug: /talks/
    title: talks
  - slug: /writing/
    title: writing
  - slug: /blog/
    title: blog
  - slug: /blog/now/
    title: now
  - slug: /blog/archive/
    title: archive
