title: Moniyum's Travels
description: >- 
  The travels of the plushie red panda 'Moniyum'. 
url     : https://glasnt.com 
baseurl : /moniyum 
title   : moniyum

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
